version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Berlin
    volumes:
      - airaware_postgres_data:/var/lib/postgresql/data
      - ./db/init/backup_utf8.sql:/docker-entrypoint-initdb.d/backup.sql:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5432:5432"

  streamlit:
    build: .
    env_file:
      - .env
    environment:
      TZ: Europe/Berlin
    depends_on:
      - db
    ports:
      - "8501:8501"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  airaware_postgres_data:
